### ISSUE TITLE
motor.rotate_left(1234)

### ISSUE THREAD

**Issue by cl0v3x** [NativeDesign/python-tmcl#14]
When I copy your example program into my python program and run it, I receive this error:

Traceback (most recent call last):
  File "c:\Users\root\Desktop\PYProgramme\motor.py", line 29, in <module>
    motor.rotate_left(1234)
AttributeError: 'Motor' object has no attribute 'rotate_left'

Does anybody have an idea on how I can fix this?

**Comment by Sofiap91** [comment]
Hi! How did you fix this?

**Comment by cl0v3x** [comment]
Hey,
the pre-programed commands like `motor.rotate_left` ect are sadly not working.
I dont remember exactly how i fiixed it but i can tell you as soon as i get to my computer in my workplace on monday.

I think it was something like skipping the pre-programed commands and talking to the motor directly using `motor.send(...)` but i will give you some detailed information and examples on monday!

**Comment by Sofiap91** [comment]
Thank you very much for your answer. I solved it cloning the repo instead of doing pip install. Only that
