### ISSUE TITLE
Setting up connection with Trinamic Motor on Linux using USB2Serial converter

### ISSUE THREAD

**Issue by nicksauerwein** [NativeDesign/python-tmcl#2]
Hey everyone,

For a project in University I am trying to drive a Trinamic stepper motor with python. I found this nice solution. I connected the motor using a Exsys EX-1309-9 (USB2RS485) to a linux machine.

I tried to run the following code:
```python
import TMCL
from serial import Serial

serial_port = Serial("/dev/ttyUSB0")
bus = TMCL.connect(serial_port)
motor = bus.get_motor(0)

motor.axis.actual_position() #this line never terminates
```
The python never terminates. The error must lie somewhere in the last line. 

When I interrupt the code I get the following error:
```python
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-7-cd4400cf90d8> in <module>()
----> 1 motor.axis.actual_position()

/home/maxk/anaconda3/lib/python3.6/site-packages/TMCL/motor.py in actual_position(self)
     61     @property
     62     def actual_position (self):
---> 63         return self.get(1)
     64 
     65     @actual_position.setter

/home/maxk/anaconda3/lib/python3.6/site-packages/TMCL/motor.py in get(self, param)
     43 
     44     def get (self, param):
---> 45         reply = self.motor.send( Command.GAP, param, self.motor.motor, 0)
     46         return reply.value
     47 

/home/maxk/anaconda3/lib/python3.6/site-packages/TMCL/motor.py in send(self, cmd, type, motorbank, value)
     14 
     15     def send (self, cmd, type, motorbank, value):
---> 16         return self.bus.send(self.address, cmd, type, motorbank, value)
     17 
     18     def stop (self):

/home/maxk/anaconda3/lib/python3.6/site-packages/TMCL/bus.py in send(self, address, command, type, motorbank, value)
     37             msg = struct.pack(MSG_STRUCTURE, address, command, type, motorbank, value, checksum)
     38             self.serial.write(msg)
---> 39             rep = self.serial.read(REPLY_LENGTH)
     40             reply = Reply(struct.unpack(REPLY_STRUCTURE, rep))
     41             return self._handle_reply(reply)

/home/maxk/anaconda3/lib/python3.6/site-packages/serial/serialposix.py in read(self, size)
    481         while len(read) < size:
    482             try:
--> 483                 ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
    484                 if self.pipe_abort_read_r in ready:
    485                     os.read(self.pipe_abort_read_r, 1000)

KeyboardInterrupt: 
```
Did anyone have this problem before? How do I set the connection up correctly. Is there somewhere a more complete documentation?

Thank you very `much.`

**Comment by alanpich** [comment]
It would seem that the motor/module is not responding to your command.
When sending a command, the code blocks until a response is received.

The line `motor = bus.get_motor(0)`  should be in the format `bus.get_motor(MODULE_SERIAL_ADDRESS)` where `MODULE_SERIAL_ADDRESS` is the serial address set on the motor module. This can be checked using the TMCL IDE.

If these addresses don't match then you are effectively sending a request to a nonexistant entity, and then waiting for eternity for it to (never) respond.

**Comment by nicksauerwein** [comment]
Ah, ok. So this means that I have to install TMCL IDE on a windows machine to extract the 'MODULE_SERIAL_ADDRESS' and then I can use this on the linux. Right?

**Comment by alanpich** [comment]
I'm afraid I don't know any easier ways of tracking it down. All the module's i've used (TMCM 1181 & 1161) have come out of the box with a serial address set to 0, but I don't know if this is guaranteed. 

While there it's also worth checking the baud rate the module is set to use and making sure that your pyserial connection matches.

What module are you trying to communicate with?

Without windows, you could try iterating through potential addresses with a timeout and see if any get a response perhaps? A lengthy process, but it should _eventually_ work.

**Comment by nicksauerwein** [comment]
I managed. I had a problem with the rs485 connection. Now it works. I there by chance an example script how to drive the motor once it is connected?

**Comment by alanpich** [comment]
I'm literally updating the examples as we speak.

Watch this space (10 mins).

**Comment by nicksauerwein** [comment]
Nice, thank you =)
