### ISSUE TITLE
Installation of package

### ISSUE THREAD

**Issue by nicksauerwein** [NativeDesign/python-tmcl#4]
Hey,

when I install using the git directly I get the following error:
```bash
[maxk@Yhen-PC python-tmcl]$ python setup.py install
running install
running bdist_egg
running egg_info
creating TMCL.egg-info
writing TMCL.egg-info/PKG-INFO
writing dependency_links to TMCL.egg-info/dependency_links.txt
writing requirements to TMCL.egg-info/requires.txt
writing top-level names to TMCL.egg-info/top_level.txt
writing manifest file 'TMCL.egg-info/SOURCES.txt'
error: package directory 'TMCL' does not exist
```

The problem seems to be the capital letters...

**Comment by alanpich** [comment]
Ah yes... almost certainly caused by me developing on a mac which has a really strange idea of case sensitivity.

- [ ]  Correct letter-casing of folder names for case-sensitive filesystems

**Comment by alanpich** [comment]
Latest commit on master should resolve this
